%YAML 1.2
---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    tag: "{{ lookup('env','TAG') }}"
    collection_dir: ../src
    ansible_python_interpreter: python

  pre_tasks:
    - name: Ensure the TAG environment variable is set.
      ansible.builtin.assert:
        that:
          - lookup('env','TAG') != ''
        fail_msg: TAG is not set.

  tasks:
    - name: Template out the galaxy.yml file.
      ansible.builtin.template:
        src: templates/galaxy.yml.j2
        dest: "{{ collection_dir ~ '/galaxy.yml' }}"
        mode: u=rw,go=r
