%YAML 1.2
---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    roles_dir: ../src/roles
    ansible_python_interpreter: python

  tasks:
    - name: Template out the vars.yml files.
      ansible.builtin.template:
        src: "{{ 'templates/' ~ item[0] }}"
        dest: "{{ roles_dir ~ '/' ~ item[1] }}"
        mode: u=rw,go=r
      loop:
        - [bond-vars.yml.j2, bond/vars/main.yml]
        - [dummy-vars.yml.j2, dummy/vars/main.yml]
        - [tunnel-vars.yml.j2, tunnel/vars/main.yml]
        - [vlan-vars.yml.j2, vlan/vars/main.yml]
      vars:
        match_system_arguments:
          host: Host
          virtualization: Virtualization
          kernel_command_line: KernelCommandLine
          kernel_version: KernelVersion
          architecture: Architecture
          firmware: Firmware
        match_device_arguments:
          mac_address: MACAddress
          permanent_mac_address: PermanentMACAddress
          path: Path
          original_name: OriginalName
        match_device_excludable_arguments:
          driver: Driver
          type: Type
          kind: Kind
          credential: Credential
        netdev_arguments:
          mac_address: MACAddress
          mtu_bytes: MTUBytes
        bond_arguments:
          mode: Mode
          transmit_hash_policy: TransmitHashPolicy
          mii_monitor_sec: MIIMonitorSec
          up_delay_sec: UpDelaySec
          down_delay_sec: DownDelaySec
          min_links: MinLinks
          lacp_transmit_rate: LACPTransmitRate
        tunnel_arguments:
          local: Local
          remote: Remote
          ttl: TTL
