%YAML 1.2
---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    tag: "{{ lookup('env','TAG') }}"
    collection_dir: ../src

  pre_tasks:
    - name: Ensure the TAG environment variable is set.
      ansible.builtin.assert:
        that:
          - lookup('env','TAG') != ''
        fail_msg: TAG is not set.

    - name: Ensure the ANSIBLE_GALAXY_TOKEN environment variable is set.
      ansible.builtin.assert:
        that:
          - lookup('env','ANSIBLE_GALAXY_TOKEN') != ''
        fail_msg: ANSIBLE_GALAXY_TOKEN is not set.

  tasks:
    - name: Get collection details.
      ansible.builtin.include_vars:
        file: "{{ collection_dir ~ '/galaxy.yml' }}"
        name: details

    - name: Build the collection.
      ansible.builtin.command:
        chdir: "{{ collection_dir }}"
        argv:
          - ansible-galaxy
          - collection
          - build

    - name: Publish the collection.
      ansible.builtin.command:
        argv:
          - ansible-galaxy
          - collection
          - publish
          - --token
          - "{{ lookup('env','ANSIBLE_GALAXY_TOKEN') }}"
          - "{{ collection_dir ~ '/' ~ details.namespace ~ '-' ~ details.name ~ '-' ~ tag ~ '.tar.gz' }}"
