%YAML 1.2
---
argument_specs:
  main:
    short_description: Manages systemd-networkd dummy virtual network devices.
    description:
      - |
        This role will create (or update) one item in /etc/systemd/network for
        each specified dummy: a .netdev file for the dummy device

      - |
        Sets fact named 'systemd_networkd_dummy_changed' to either true or false to indicate whether
        any changes were made.
    options:
      suppress_reload:
        description: Suppress the reloading of systemd-networkd if changes are made.
        type: bool
        default: false
      systemd_root:
        description: Root path of filesystem containing systemd-networkd configuration files.
        type: str
        default: ""
      dummies:
        description: Attributes of the dummy devices to be managed.
        type: list
        elements: dict
        required: true
        options:
          name:
            description: Name of the network device.
            type: str
            required: true
          match:
            description: Matching attributes of the network device.
            type: dict
            options:
              system:
                description: System-specific attributes to be matched.
                type: dict
                options:
                  architecture:
                    description: Match system architecture.
                    type: str
                  credential:
                    description: Match service credential.
                    type: str
                  firmware:
                    description: Match system firmware.
                    type: str
                  host:
                    description: Match hostname or machine ID.
                    type: str
                  kernel_command_line:
                    description: Match kernel command line option presence.
                    type: str
                  kernel_version:
                    description: Match kernel version expression.
                    type: str
                  virtualization:
                    description: Match virtualization type.
                    type: str
