%YAML 1.2
---
argument_specs:
  main:
    short_description: Manages systemd-networkd dummy virtual network devices.
    description: |
      This role will create (or update) one item in /etc/systemd/network for
      each specified dummy: a .netdev file for the dummy device
    options:
      dummies:
        description: Attributes of the dummy devices to be managed.
        type: list
        elements: dict
        required: true
        options:
          name:
            description: Name of the network device.
            type: str
            required: true
          match:
            description: Matching attributes of the network device.
            type: dict
            options:
              host:
                description: Match hostname or machine ID.
                type: str
              exclude_host:
                description: Negate 'host' match.
                type: bool
              virtualization:
                description: Match virtualization type.
                type: str
              exclude_virtualization:
                description: Negate 'virtualization' match.
                type: bool
              kernel_command_line:
                description: Match kernel command line option presence.
                type: str
              exclude_kernel_command_line:
                description: Negate 'kernel_command_line' match.
                type: bool
              kernel_version:
                description: Match kernel version expression.
                type: str
              exclude_kernel_version:
                description: Negate 'kernel_version' match.
                type: bool
              architecture:
                description: Match system architecture.
                type: str
              exclude_architecture:
                description: Negate 'architecture' match.
                type: bool
              firmware:
                description: Match system firmware.
                type: str
              exclude_firmware:
                description: Negate 'firmware' match.
                type: bool
