%YAML 1.2
---
- name: manage network device for dummy
  notify: "{{ ansible_role_name ~ ' : reload' }}"
  ansible.builtin.template:
    src: dummy.netdev.j2
    dest: "{{ '/etc/systemd/network/' ~ dummy.name ~ '.netdev' }}"
    mode: u=rw,go=r
