---
- name: manage dummy interfaces
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/dummy.yml"
  loop: "{{ dummies }}"
  loop_control:
    loop_var: dummy
    label: "{{ dummy.name }}"

- name: run handlers if needed
  ansible.builtin.meta: flush_handlers
