%YAML 1.2
---
- name: manage dummy interfaces
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/dummy.yml"
  loop: "{{ dummies }}"
  loop_control:
    loop_var: dummy

- name: run handlers if needed
  ansible.builtin.meta: flush_handlers
