---
argument_specs:
  main:
    short_description: Manages systemd-networkd bonded network devices.
    description:
      - |
        This role will create (or update) a number of items in /etc/systemd/network for
        each specified bonded device:
        1) A .netdev file for the bond device
        2) .network files for each link that is a member of the bond; files will be named
        with the bond device's name and a numeric suffix
        3) .link files for each interface that is a member of the bond; files will be named
        with the bond device's name and a numeric suffix

      - |
        On Debian and Debian-derivative systems the .link files are
        copied into the initramfs by the `update-initramfs` tool, which
        means that the system must be rebooted for changes in those
        files to take effect. In this situation the role will set a fact
        named 'systemd_networkd_link_reboot_required' and the system
        should be rebooted before any additional configuration of the
        bonded network links is attempted.

      - |
        Detailed descriptions of parameters and their behavior can be found in 'man systemd.netdev'
        and 'man systemd.link'.

      - |
        Sets fact named 'systemd_networkd_bond_changed' to either true or false to indicate whether
        any changes were made.
    options:
      suppress_reload:
        description: Suppress the reloading of systemd-networkd if changes are made.
        type: bool
        default: false
      systemd_root:
        description: Root path of filesystem containing systemd-networkd configuration files.
        type: str
        default: ""
      bonds:
        description: Attributes of the bond devices to be managed.
        type: list
        elements: dict
        required: true
        options:
          name:
            description: Name of the bond device.
            type: str
            required: true
          bond:
            description: Attributes of the bond device.
            type: dict
            options:
              mode:
                description: Bonding mode.
                type: str
                choices:
                  - balance-rr
                  - active-backup
                  - balance-xor
                  - broadcast
                  - 802.3ad
                  - balance-tlb
                  - balance-alb
              transmit_hash_policy:
                description: Policy for member selection during transmit.
                type: str
                choices:
                  - layer2
                  - layer3+4
                  - layer2+3
                  - encap2+3
                  - encap3+4
              lacp_transmit_rate:
                description: LACP data unit transmission rate (only used in 802.3ad mode).
                type: str
                choices:
                  - slow
                  - fast
              mii_monitor_sec:
                description: Frequency of MII link monitoring.
                type: str
              min_links:
                description: Minimum number of active members for the device to report that it 'has carrier'.
                type: int
              up_delay_sec:
                description: Delay between the minimum number of members reaching 'link up' and 'link up' being reported for the bond.
                type: str
              down_delay_sec:
                description: Delay between the minimum number of members reaching 'link down' and 'link down' being reported for the bond.
                type: str
          netdev:
            description: Attributes of the bond network device.
            type: dict
            options:
              mac_address:
                description: MAC address to use on the device.
                type: str
              mtu_bytes:
                description: The MTU for the device.
                type: str
          match:
            description: Matching attributes of the bond network device.
            type: dict
            options:
              system:
                description: System-specific attributes to be matched.
                type: dict
                options:
                  architecture:
                    description: Match system architecture.
                    type: str
                  credential:
                    description: Match service credential.
                    type: str
                  firmware:
                    description: Match system firmware.
                    type: str
                  host:
                    description: Match hostname or machine ID.
                    type: str
                  kernel_command_line:
                    description: Match kernel command line option presence.
                    type: str
                  kernel_version:
                    description: Match kernel version expression.
                    type: str
                  virtualization:
                    description: Match virtualization type.
                    type: str
          members:
            description: Matching attributes of the bond's member interfaces.
            type: list
            elements: dict
            required: true
            options:
              device:
                description: Device-specific attributes to be matched.
                type: dict
                options:
                  driver:
                    description: Match udev ID_NET_DRIVER.
                    type: list
                    elements: str
                  kind:
                    description: Match netlink IFLA_INFO_KIND.
                    type: list
                    elements: str
                  mac_address:
                    description: Match current MAC address.
                    type: list
                    elements: str
                  original_name:
                    description: Match udev INTERFACE.
                    type: list
                    elements: str
                  path:
                    description: Match udev ID_PATH.
                    type: list
                    elements: str
                  permanent_mac_address:
                    description: Match permanent MAC address.
                    type: list
                    elements: str
                  property:
                    description: Match udev property.
                    type: list
                    elements: str
                  type:
                    description: Match udev DEVTYPE.
                    type: list
                    elements: str
              system:
                description: System-specific attributes to be matched.
                type: dict
                options:
                  architecture:
                    description: Match system architecture.
                    type: str
                  credential:
                    description: Match service credential.
                    type: str
                  firmware:
                    description: Match system firmware.
                    type: str
                  host:
                    description: Match hostname or machine ID.
                    type: str
                  kernel_command_line:
                    description: Match kernel command line option presence.
                    type: str
                  kernel_version:
                    description: Match kernel version expression.
                    type: str
                  virtualization:
                    description: Match virtualization type.
                    type: str
