%YAML 1.2
---
- name: manage network
  register: _network
  notify: "{{ ansible_role_name ~ ' : reload' }}"
  ansible.builtin.template:
    src: network.j2
    dest: "{{ systemd_root ~ '/etc/systemd/network/' ~ network.name ~ '.network' }}"
    mode: u=rw,go=r
