%YAML 1.2
---
- name: manage network drop-in directory
  ansible.builtin.file:
    path: "{{ systemd_root ~ '/etc/systemd/network/' ~ network.name ~ '.network.d' }}"
    state: directory
    mode: u=rwx,go=rx

- name: manage network
  register: _network
  notify: "{{ ansible_role_name ~ ' : reload' }}"
  ansible.builtin.template:
    src: network.j2
    dest: "{{ systemd_root ~ '/etc/systemd/network/' ~ network.name ~ '.network' }}"
    mode: u=rw,go=r

- name: set fact to indicate result
  ansible.builtin.set_fact:
    systemd_networkd_network_changed: "{{ systemd_networkd_network_changed|default(false) or _network.changed }}"
