%YAML 1.2
---
match_system_arguments:
  host: Host
  virtualization: Virtualization
  kernel_command_line: KernelCommandLine
  kernel_version: KernelVersion
  architecture: Architecture
  firmware: Firmware

netdev_arguments:
  mac_address: MACAddress
  mtu_bytes: MTUBytes

tunnel_arguments:
  local: Local
  remote: Remote
  ttl: TTL
