%YAML 1.2
---
match_system_arguments:
  host: Host
  virtualization: Virtualization
  kernel_command_line: KernelCommandLine
  kernel_version: KernelVersion
  architecture: Architecture
  firmware: Firmware

match_device_arguments:
  mac_address: MACAddress
  permanent_mac_address: PermanentMACAddress
  path: Path
  original_name: OriginalName

match_device_excludable_arguments:
  driver: Driver
  type: Type
  kind: Kind
  credential: Credential

netdev_arguments:
  mac_address: MACAddress

bond_arguments:
  mode: Mode
  transmit_hash_policy: TransmitHashPolicy
  mii_monitor_sec: MIIMonitorSec
  up_delay_sec: UpDelaySec
  down_delay_sec: DownDelaySec
  min_links: MinLinks
  lacp_transmit_rate: LACPTransmitRate
