%YAML 1.2
---
argument_specs:
  main:
    short_description: Manages systemd-networkd VLAN virtual network devices.
    description: |
      This role will create (or update) three items in /etc/systemd/network for
      each specified VLAN:
      1) A drop-in directory for the underlying network
      2) A .netdev file for the VLAN device
      3) A .conf file in the drop-in directory connecting the VLAN device
      to the underlying network

      Detailed descriptions of parameters and their behavior can be found in 'man systemd.netdev'.

      Sets fact named 'systemd_networkd_vlan_changed' to either true or false to indicate whether
      any changes were made.
    options:
      suppress_reload:
        description: Suppress the reloading of systemd-networkd if changes are made.
        type: bool
        default: false
      systemd_root:
        description: Root path of filesystem containing systemd-networkd configuration files.
        type: str
        default: ""
      vlans:
        description: Attributes of the devices to be managed.
        type: list
        elements: dict
        required: true
        options:
          name:
            description: Name of the network device.
            type: str
            required: true
          id:
            description: The VLAN ID number (1-4095).
            type: int
            required: true
          underlying_name:
            description: The underlying network.
            type: str
            required: true
          match:
            description: Matching attributes of the network device.
            type: dict
            options:
              host:
                description: Match hostname or machine ID.
                type: str
              exclude_host:
                description: Negate 'host' match.
                type: bool
              virtualization:
                description: Match virtualization type.
                type: str
              exclude_virtualization:
                description: Negate 'virtualization' match.
                type: bool
              kernel_command_line:
                description: Match kernel command line option presence.
                type: str
              exclude_kernel_command_line:
                description: Negate 'kernel_command_line' match.
                type: bool
              kernel_version:
                description: Match kernel version expression.
                type: str
              exclude_kernel_version:
                description: Negate 'kernel_version' match.
                type: bool
              architecture:
                description: Match system architecture.
                type: str
              exclude_architecture:
                description: Negate 'architecture' match.
                type: bool
              firmware:
                description: Match system firmware.
                type: str
              exclude_firmware:
                description: Negate 'firmware' match.
                type: bool
