---
argument_specs:
  main:
    short_description: Manages systemd-networkd global configuration.
    description:
      - |
        This role will create (or update) a dropin file named ansible.conf in /etc/systemd/networkd.conf.d

      - |
        Sets fact named 'systemd_networkd_global_changed' to either true or false to indicate whether
        any changes were made.
    options:
      suppress_reload:
        description: Suppress the reloading of systemd-networkd if changes are made.
        type: bool
        default: false
      systemd_root:
        description: Root path of filesystem containing systemd-networkd configuration files.
        type: str
        default: ""
      settings:
        description: Settings to be applied globally.
        type: dict
        required: true
        options:
          network:
            description: Settings for the Network section.
            type: dict
            options:
              ipv4_forwarding:
                description: Enable IPv4 forwarding.
                type: bool
              ipv6_forwarding:
                description: Enable IPv6 forwarding.
                type: bool
