---
- name: manage WireGuard tunnel devices
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/wireguard.yml"
  loop: "{{ wireguards }}"
  loop_control:
    loop_var: wireguard
    label: "{{ wireguard.name }}"

- name: run handlers if needed
  ansible.builtin.meta: flush_handlers
