%YAML 1.2
---
match_system_arguments:
  host: Host
  virtualization: Virtualization
  kernel_command_line: KernelCommandLine
  kernel_version: KernelVersion
  architecture: Architecture
  firmware: Firmware
