%YAML 1.2
---
- name: manage WireGuard tunnel devices
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/wireguard_tunnel.yml"
  loop: "{{ wireguard_tunnels }}"
  loop_control:
    loop_var: tunnel
    label: "{{ tunnel.name }}"

- name: run handlers if needed
  ansible.builtin.meta: flush_handlers
