---
argument_specs:
  main:
    short_description: Manages systemd-networkd links.
    description:
      - |
        This role will create (or update) one item in /etc/systemd/network for
        each specified link: a .link file for the link.

      - |
        On Debian and Debian-derivative systems the .link files are
        copied into the initramfs by the `update-initramfs` tool, which
        means that the system must be rebooted for changes in those
        files to take effect. In this situation the role will set a fact
        named 'systemd_networkd_link_reboot_required' and the system
        should be rebooted before any additional configuration of the
        links is attempted.

      - |
        Detailed descriptions of parameters and their behavior can be found in 'man systemd.link'.

      - |
        Sets fact named 'systemd_networkd_link_changed' to either true or false to indicate whether
        any changes were made.
    options:
      suppress_reload:
        description: Suppress the reloading of systemd-networkd if changes are made.
        type: bool
        default: false
      systemd_root:
        description: Root path of filesystem containing systemd-networkd configuration files.
        type: str
        default: ""
      links:
        description: Attributes of the links to be managed.
        type: list
        elements: dict
        required: true
        options:
          name:
            description: Name of the link.
            type: str
          link:
            description: Attributes of the link.
            type: dict
            options:
              mac_address_policy:
                description: Policy for setting the MAC address of the link.
                type: str
                choices:
                  - persistent
                  - random
                  - none
              name_policy:
                description: Policy for setting the name of the link.
                type: str
                choices:
                  - kernel
                  - database
                  - onboard
                  - slot
                  - path
                  - mac
                  - keep
              mtu_bytes:
                description: The MTU for the link.
                type: str
          match:
            description: Matching attributes of the link.
            type: dict
            options:
              device:
                description: Device-specific attributes to be matched.
                type: dict
                options:
                  driver:
                    description: Match udev ID_NET_DRIVER.
                    type: list
                    elements: str
                  kind:
                    description: Match netlink IFLA_INFO_KIND.
                    type: list
                    elements: str
                  mac_address:
                    description: Match current MAC address.
                    type: list
                    elements: str
                  original_name:
                    description: Match udev INTERFACE.
                    type: list
                    elements: str
                  path:
                    description: Match udev ID_PATH.
                    type: list
                    elements: str
                  permanent_mac_address:
                    description: Match permanent MAC address.
                    type: list
                    elements: str
                  property:
                    description: Match udev property.
                    type: list
                    elements: str
                  type:
                    description: Match udev DEVTYPE.
                    type: list
                    elements: str
              system:
                description: System-specific attributes to be matched.
                type: dict
                options:
                  architecture:
                    description: Match system architecture.
                    type: str
                  credential:
                    description: Match service credential.
                    type: str
                  firmware:
                    description: Match system firmware.
                    type: str
                  host:
                    description: Match hostname or machine ID.
                    type: str
                  kernel_command_line:
                    description: Match kernel command line option presence.
                    type: str
                  kernel_version:
                    description: Match kernel version expression.
                    type: str
                  virtualization:
                    description: Match virtualization type.
                    type: str
