%YAML 1.2
---
- name: manage tunnel devices
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/tunnel.yml"
  loop: "{{ tunnels }}"
  loop_control:
    loop_var: tunnel
    label: "{{ tunnel.name }}"

- name: run handlers if needed
  ansible.builtin.meta: flush_handlers
