%YAML 1.2
---
- name: manage bond member names
  ansible.builtin.include_role:
    name: kpfleming.systemd_networkd.link
    tasks_from: link.yml
  vars:
    link:
      name: "{{ bond.name ~ '-' ~ ansible_loop.index }}"
      match: "{{ member }}"
  loop: "{{ bond.members }}"
  loop_control:
    loop_var: member
    extended: true

- name: manage bond member networks
  notify: "{{ ansible_role_name ~ ' : reload' }}"
  ansible.builtin.template:
    src: bond-member.network.j2
    dest: "{{ '/etc/systemd/network/' ~ bond.name ~ '-' ~ ansible_loop.index ~ '.network' }}"
    mode: u=rw,go=r
  loop: "{{ bond.members }}"
  loop_control:
    loop_var: member
    extended: true

- name: manage bond network device
  notify: "{{ ansible_role_name ~ ' : reload' }}"
  ansible.builtin.template:
    src: bond.netdev.j2
    dest: "{{ '/etc/systemd/network/' ~ bond.name ~ '.netdev' }}"
    mode: u=rw,go=r
