%YAML 1.2
---
- name: manage bond member names
  register: _link
  ansible.builtin.include_role:
    name: kpfleming.systemd_networkd.link
    tasks_from: link.yml
  vars:
    link:
      name: "{{ bond.name ~ '-' ~ ansible_loop.index }}"
      match: "{{ member }}"
  loop: "{{ bond.members }}"
  loop_control:
    loop_var: member
    extended: true

- name: manage bond member networks
  become: true
  register: _member
  notify: "{{ ansible_role_name ~ ' : reload' }}"
  ansible.builtin.template:
    src: bond-member.network.j2
    dest: "{{ systemd_root ~ '/etc/systemd/network/' ~ bond.name ~ '-' ~ ansible_loop.index ~ '.network' }}"
    mode: u=rw,g=r
    group: systemd-network
  loop: "{{ bond.members }}"
  loop_control:
    loop_var: member
    extended: true

- name: manage bond network device
  become: true
  register: _netdev
  notify: "{{ ansible_role_name ~ ' : reload' }}"
  ansible.builtin.template:
    src: bond.netdev.j2
    dest: "{{ systemd_root ~ '/etc/systemd/network/' ~ bond.name ~ '.netdev' }}"
    mode: u=rw,g=r
    group: systemd-network

- name: set fact to indicate result
  ansible.builtin.set_fact:
    systemd_networkd_bond_changed: "{{ systemd_networkd_bond_changed|default(false) or _link.changed or _member.changed or _netdev.changed }}"
