---
- name: manage bond devices
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/bond.yml"
  loop: "{{ bonds }}"
  loop_control:
    loop_var: bond
    label: "{{ bond.name }}"

- name: run handlers if needed
  ansible.builtin.meta: flush_handlers
