name: CI

on:
  push:
    branches:
    - main
    paths:
    - '*.py'
    - 'api-swagger.json'
    - 'tox.ini'
    - 'workflow-support/test-*.yml'
    - 'workflow-support/make_ci_image.sh'
    - 'workflow-support/start_server.sh'
    - 'workflow-support/versions.json'
    - '.github/workflows/ci.yml'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
    paths:
    - '*.py'
    - 'api-swagger.json'
    - 'tox.ini'
    - 'workflow-support/test-*.yml'
    - 'workflow-support/make_ci_image.sh'
    - 'workflow-support/start_server.sh'
    - 'workflow-support/versions.json'
    - '.github/workflows/ci.yml'
  schedule:
    - cron: "35 4 * * 6"

jobs:
  preflight:
    runs-on: ubuntu-20.04
    outputs:
      image_registry: ${{ steps.details.outputs.image_registry }}
      image_base: ${{ steps.details.outputs.image_registry }}/${{ steps.details.outputs.registry_account }}/${{ steps.details.outputs.repo_name }}
      base_image: ${{ steps.details.outputs.image_registry }}/${{ steps.details.outputs.registry_account }}/python
      need_image: ${{ steps.preflight.outputs.need_image }}
      image_tag: ${{ steps.preflight.outputs.image_tag }}
      versions: ${{ steps.get_versions.outputs.versions }}
    steps:
    - id: details
      uses: kpfleming/composite-actions/image-details@main
    - id: preflight
      uses: kpfleming/composite-actions/ci-preflight@main
    - id: get_versions
      run: cat workflow-support/versions.json >> $GITHUB_OUTPUT
  ci-image:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    steps:
    - uses: actions/checkout@v3
    - uses: kpfleming/composite-actions/make-ci-image@main
      if: needs.preflight.outputs.need_image == 'true'
      with:
        files_hash: ${{ hashfiles('tox.ini', 'workflow-support/make_ci_image.sh', 'workflow-support/versions.json') }}
        build_args: ${{ join(fromJSON(needs.preflight.outputs.versions).pdns, ' ') }}
        base_image: ${{ needs.preflight.outputs.base_image }}
        image_name: ${{ needs.preflight.outputs.image_base }}:${{ needs.preflight.outputs.image_tag }}
        image_registry: ${{ needs.preflight.outputs.image_registry }}
        registry_username: ${{ secrets.QUAY_BOT_NAME }}
        registry_password: ${{ secrets.QUAY_BOT_PASSWORD }}
  test:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    - ci-image
    strategy:
      matrix:
        pdns: ${{ fromJSON(needs.preflight.outputs.versions).pdns }}
        python: ${{ fromJSON(needs.preflight.outputs.versions).python }}
      fail-fast: false
    container:
      image: ${{ needs.preflight.outputs.image_base }}:${{ needs.preflight.outputs.image_tag }}
    steps:
    - uses: actions/checkout@v3
    - name: start pdns_server
      run: workflow-support/start_server.sh ${{ matrix.pdns }}
    - name: run tests
      run: tox -e${{ matrix.python }}-ansible --workdir /root/tox
      env:
        pdns_version: ${{ matrix.pdns }}
