name: CI

on:
  push:
    branches:
    - main
    paths:
    - 'src/**.yml'
    - 'tox.ini'
    - 'workflow-support/make-vars-yml.yml'
    - 'workflow-support/templates/*-vars.yml.j2'
    - 'workflow-support/make_ci_image.sh'
    - '.github/workflows/ci.yml'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
    paths:
    - 'src/**.yml'
    - 'tox.ini'
    - 'workflow-support/make-vars-yml.yml'
    - 'workflow-support/templates/*-vars.yml.j2'
    - 'workflow-support/make_ci_image.sh'
    - '.github/workflows/ci.yml'
  schedule:
    - cron: "35 4 * * 6"

jobs:
  preflight:
    runs-on: ubuntu-22.04
    outputs:
      image_registry: ${{ steps.details.outputs.image_registry }}
      image_base: ${{ steps.details.outputs.image_registry }}/${{ steps.details.outputs.registry_account }}/${{ steps.details.outputs.repo_name }}
      base_image: ${{ steps.details.outputs.image_registry }}/${{ steps.details.outputs.registry_account }}/python
      need_image: ${{ steps.preflight.outputs.need_image }}
      image_tag: ${{ steps.preflight.outputs.image_tag }}
      versions: ${{ steps.get_versions.outputs.versions }}
    steps:
    - id: details
      uses: kpfleming/composite-actions/image-details@main
    - id: preflight
      uses: kpfleming/composite-actions/ci-preflight@main
  ci-image:
    runs-on: ubuntu-22.04
    needs:
    - preflight
    steps:
    - uses: actions/checkout@v3
    - uses: kpfleming/composite-actions/make-ci-image@main
      if: needs.preflight.outputs.need_image == 'true'
      with:
        files_hash: ${{ hashfiles('tox.ini', 'workflow-support/make_ci_image.sh') }}
        base_image: ${{ needs.preflight.outputs.base_image }}
        image_name: ${{ needs.preflight.outputs.image_base }}:${{ needs.preflight.outputs.image_tag }}
        image_registry: ${{ needs.preflight.outputs.image_registry }}
        registry_username: ${{ secrets.QUAY_BOT_NAME }}
        registry_password: ${{ secrets.QUAY_BOT_PASSWORD }}
