name: Delete PR Image

on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  clean-image:
    runs-on: ubuntu-20.04
    steps:
    - id: details
      uses: kpfleming/composite-actions/image-details@main
    - uses: kpfleming/composite-actions/delete-pr-image@main
      with:
        image_registry: ${{ steps.details.outputs.image_registry }}
        registry_account: ${{ steps.details.outputs.registry_account }}
        registry_token: ${{ secrets.QUAY_API_TOKEN }}
        repo_name: ${{ steps.details.outputs.repo_name }}
