name: Lint checks

on:
  pull_request:
    branches:
    - main

jobs:
  check_paths:
    runs-on: ubuntu-22.04
    outputs:
      need_lint: ${{ steps.paths.outputs.paths }}
    steps:
    - uses: actions/checkout@v3
    - id: paths
      uses: dorny/paths-filter@v2
      with:
        filters: |
          paths:
          - 'src/**.yml'
          - 'tox.ini'
          - 'workflow-support/*.sh'
          - 'workflow-support/*.yml'
          - 'workflow-support/templates/*-vars.yml.j2'
          - '.github/workflows/lint.yml'
  image_details:
    if: needs.check_paths.outputs.need_lint == 'true'
    runs-on: ubuntu-22.04
    needs:
    - check_paths
    outputs:
      image_base: ${{ steps.details.outputs.image_base }}
    steps:
    - id: details
      uses: kpfleming/composite-actions/image-details@main
  lint:
    if: needs.check_paths.outputs.need_lint == 'true'
    runs-on: ubuntu-22.04
    needs:
    - check_paths
    - image_details
    container:
      image: ${{ needs.image_details.outputs.image_base }}:main
    steps:
    - uses: actions/checkout@v3
    - uses: kpfleming/composite-actions/lint-tox@main
