name: CI tests

on:
  workflow_call:
    inputs:
      if:
        required: false
        default: true
        type: boolean
      image:
        required: true
        type: string
      python:
        required: true
        type: string

jobs:
  test:
    if: inputs.if
    runs-on: ubuntu-24.04-arm
    container:
      image: ${{ inputs.image }}
    steps:
    - uses: actions/checkout@v5
      with:
        show-progress: false
    - uses: kpfleming/composite-actions/ci-tox@v3
      with:
        python: ${{ inputs.python }}
