%YAML 1.2
---
- name: manage link
  register: _link
  notify: "{{ ansible_role_name ~ ' : reload' }}"
  ansible.builtin.template:
    src: link.j2
    dest: "{{ '/etc/systemd/network/00-' ~ link.name ~ '.link' }}"
    mode: u=rw,go=r

- name: set reboot fact
  when: ansible_distribution == "Debian"
  ansible.builtin.set_fact:
    systemd_networkd_link_reboot_required: "{{ systemd_networkd_link_reboot_required|default(false) or _link.changed }}"
