%YAML 1.2
---
- name: manage VLAN devices
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/vlan.yml"
  loop: "{{ vlans }}"
  loop_control:
    loop_var: vlan
    label: "{{ vlan.name }}"

- name: run handlers if needed
  ansible.builtin.meta: flush_handlers
